version: "3.9" # optional since v1.27.0

services:
  llama-bot:
    container_name: llama-bot
    hostname: llama-bot
    build:
      context: ./llama-bot
      dockerfile: Dockerfile
    env_file: llama-bot/.env
    # volumes:
    #   - .llama-bot:/app
  llama-bot-api:
    container_name: llama-bot-api
    hostname: llama-bot-api
    build:
      context: ./llama-bot-api
      dockerfile: Dockerfile
    # volumes:
    #   - ./llama-bot-api/src/:/usr/src/app/
    #   - /usr/src/app/node_modules
    env_file: llama-bot-api/.env
    restart: unless-stopped
    depends_on:
      - llama-bot-db
  llama-bot-db:
    container_name: llama-bot-db
    hostname: llama-bot-db
    image: postgres
    volumes:
      - ./volume:/var/lib/postgresql
    environment:
      - POSTGRES_DB=llama-bot-database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 54321:5432
    restart: unless-stopped
  llama-bot-client:
    container_name: llama-bot-client
    hostname: llama-bot-client
    build:
      context: ./llama-bot-client
      dockerfile: Dockerfile
    env_file: llama-bot-client/.env
    ports:
      - 4200:80
    restart: always
    depends_on:
      - llama-bot-api
