version: "3.9" # optional since v1.27.0

services:
  llama-bot:
    container_name: llama-bot
    hostname: llama-bot
    build:
      dockerfile: ./packages/llama-bot/Dockerfile
    depends_on:
      - llama-bot-db
    env_file: packages/llama-bot/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://root:root@llama-bot-db:5432/llama-bot-db
    networks:
      - default
    restart: unless-stopped
  llama-bot-api:
    container_name: llama-bot-api
    hostname: llama-bot-api
    build:
      dockerfile: ./packages/llama-bot-api/Dockerfile
    depends_on:
      - llama-bot-db
    env_file: packages/llama-bot-api/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://root:root@llama-bot-db:5432/llama-bot-db
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      - default
    restart: unless-stopped
  llama-bot-db:
    container_name: llama-bot-db
    hostname: llama-bot-db
    image: postgres:15.1
    volumes:
      - ./volume:/var/lib/postgresql
    environment:
      - POSTGRES_DB=llama-bot-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 54321:54321
    networks:
      - default
    restart: unless-stopped
  llama-bot-client:
    container_name: llama-bot-client
    hostname: llama-bot-client
    build:
      dockerfile: ./packages/llama-bot-client/Dockerfile
    depends_on:
      - llama-bot-api
    environment:
      - API_URL=llama-bot-api:8080
    ports:
      - 4200:80
    networks:
      - default
    restart: always
