version: 2.1

orbs:
  heroku-orb: circleci/heroku@1.2.6 # Invoke the Heroku orb

executors:
  llama-bot-docker-executor:
    docker:
      - image: cimg/node:14.17.6
    working_directory: ~/llama-bot-discord/llama-bot
  llama-bot-api-docker-executor:
    docker:
      - image: cimg/node:14.17.6
    working_directory: ~/llama-bot-discord/llama-bot-api
      
jobs:
  # llama-bot
  llama-bot-install:
    executor: llama-bot-docker-executor
    steps:
      - checkout:
          path: ~/llama-bot-discord
      # Try to restore dependencies from cache
      - restore_cache:
          keys:
            - llama-bot-nodemodules-v1-{{ checksum "package-lock.json" }}
            - llama-bot-nodemodules-v1-
      - run:
          name: Install dependencies
          command: npm install
      # Update dependencies cache
      - save_cache:
          key: llama-bot-nodemodules-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # Save current workflow installed state in cache
      # .Environment.CIRCLE_SHA1 makes it unique for each build
      - save_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./
  llama-bot-lint:
    executor: llama-bot-docker-executor
    steps:
      - restore_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: npm run lint
  llama-bot-test:
    executor: llama-bot-docker-executor
    working_directory: llama-bot
    steps:
      - restore_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build
          command: npm build
  llama-bot-build-publish:
    executor: llama-bot-docker-executor
    working_directory: llama-bot
    environment:
      HEROKU_APP_NAME: "llama-bot-discord"
    steps:
      - restore_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
      # Deploy to Heroku
      - heroku-orb/install
      - run: heroku container:login
      # Push built image to heroku container registry
      - heroku/push-docker-image:
          process-types: llama-bot
      # Release the pushed image (aka deploy)
      # - heroku/release-docker-image:
      #     process-types: llama-bot
  # llama-bot-api
  llama-bot-api-install:
    executor: llama-bot-api-docker-executor
    steps:
      - checkout:
          path: ~/llama-bot-discord
      # Try to restore dependencies from cache
      - restore_cache:
          keys:
            - llama-bot-api-nodemodules-v1-{{ checksum "package-lock.json" }}
            - llama-bot-api-nodemodules-v1-
      - run:
          name: Install dependencies
          command: npm install
      # Update dependencies cache
      - save_cache:
          key: llama-bot-api-nodemodules-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # Save current workflow installed state in cache
      # .Environment.CIRCLE_SHA1 makes it unique for each build
      - save_cache:
          key: llama-bot-api-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./
  llama-bot-api-lint:
    executor: llama-bot-api-docker-executor
    steps:
      - restore_cache:
          key: llama-bot-api-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: npm run lint
  llama-bot-api-test:
    executor: llama-bot-api-docker-executor
    working_directory: llama-bot-api
    steps:
      - restore_cache:
          key: llama-bot-api-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build
          command: npm build
  llama-bot-api-build-publish:
    executor: llama-bot-api-docker-executor
    working_directory: llama-bot-api
    environment:
      HEROKU_APP_NAME: "llama-bot-discord"
    steps:
      - restore_cache:
          key: llama-bot-api-{{ .Environment.CIRCLE_SHA1 }}
      # Deploy to Heroku
      - heroku-orb/install
      - run: heroku container:login
      # Push built image to heroku container registry
      - heroku/push-docker-image:
          process-types: llama-bot-api
      # Release the pushed image (aka deploy)
      # - heroku/release-docker-image:
      #     process-types: llama-bot-api

workflows:
  version: 2
  llama-bot:
    jobs:
      - llama-bot-install
      - llama-bot-lint:
          requires:
            - llama-bot-install
      - llama-bot-test:
          requires:
            - llama-bot-install
      - llama-bot-build-publish:
        - requires:
          - llama-bot-lint
          - llama-bot-test
  llama-bot-api:
    jobs:
      - llama-bot-api-lint
      - llama-bot-api-test
      - llama-bot-api-build-publish:
        - requires:
          - llama-bot-api-lint
          - llama-bot-api-test
  # llama-bot-client:
  #   jobs:
  #     - llama-bot-api-lint
  #     - llama-bot-api-test
  #     - llama-bot-api-build
  #     - llama-bot-api-publish:
  #       - requires:
  #         - llama-bot-api-test
  #         - llama-bot-api-build
