version: 2.1

executors:
  llama-bot-docker-executor:
    docker:
      - image: cimg/node:14.17.6
    working_directory: ~/llama-bot-discord/llama-bot
  llama-bot-api-docker-executor:
    docker:
      - image: cimg/node:14.17.6
    working_directory: ~/llama-bot-discord/llama-bot-api
      
jobs:
  # llama-bot
  llama-bot-install:
    executor: llama-bot-docker-executor
    steps:
      - checkout:
          path: ~/llama-bot-discord
      # Try to restore dependencies from cache
      - restore_cache:
          keys:
            - llama-bot-nodemodules-v1-{{ checksum "package-lock.json" }}
            - llama-bot-nodemodules-v1-
      - run:
          name: Install dependencies
          command: npm install
      # Update dependencies cache
      - save_cache:
          key: llama-bot-nodemodules-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # Save current workflow installed state in cache
      # .Environment.CIRCLE_SHA1 makes it unique for each build
      - save_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./
  llama-bot-lint:
    executor: llama-bot-docker-executor
    steps:
      - restore_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: npm run lint
  llama-bot-test:
    executor: llama-bot-docker-executor
    working_directory: llama-bot
    steps:
      - restore_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: npm run test
  llama-bot-build-publish:
    executor: llama-bot-docker-executor
    working_directory: llama-bot
    steps:
      - restore_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Debug
          command: ls
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build docker image
          command: docker build -t registry.digitalocean.com/llama-bot-discord/llama-bot:${{ .Environment.CIRCLE_SHA1 }} .
      - run:
          name: Log in to DO Container Registry
          command: docker run --rm --interactive --tty --env=DIGITALOCEAN_ACCESS_TOKEN=$DO_TOKEN digitalocean/doctl registry login
      - run:
          name: Push image to DO Container Registry
          command: docker push registry.digitalocean.com/llama-bot-discord/llama-bot:${{ .Environment.CIRCLE_SHA1 }}
  # llama-bot-api
  llama-bot-api-install:
    executor: llama-bot-api-docker-executor
    steps:
      - checkout:
          path: ~/llama-bot-discord
      # Try to restore dependencies from cache
      - restore_cache:
          keys:
            - llama-bot-api-nodemodules-v1-{{ checksum "package-lock.json" }}
            - llama-bot-api-nodemodules-v1-
      - run:
          name: Install dependencies
          command: npm install
      # Update dependencies cache
      - save_cache:
          key: llama-bot-api-nodemodules-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # Save current workflow installed state in cache
      # .Environment.CIRCLE_SHA1 makes it unique for each build
      - save_cache:
          key: llama-bot-api-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./
  llama-bot-api-lint:
    executor: llama-bot-api-docker-executor
    steps:
      - restore_cache:
          key: llama-bot-api-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: npm run lint
  llama-bot-api-test:
    executor: llama-bot-api-docker-executor
    working_directory: llama-bot-api
    steps:
      - restore_cache:
          key: llama-bot-api-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build
          command: npm build
  llama-bot-api-build-publish:
    executor: llama-bot-api-docker-executor
    working_directory: llama-bot-api
    steps:
      - restore_cache:
          key: llama-bot-api-{{ .Environment.CIRCLE_SHA1 }}

workflows:
  version: 2
  llama-bot:
    jobs:
      # - llama-bot-install
      # - llama-bot-lint:
      #     requires:
      #       - llama-bot-install
      # - llama-bot-test:
      #     requires:
      #       - llama-bot-install
      - llama-bot-build-publish:
          # requires:
          #   - llama-bot-lint
          #   - llama-bot-test
  # llama-bot-api:
  #   jobs:
  #     - llama-bot-api-lint
  #     - llama-bot-api-test
  #     - llama-bot-api-build-publish:
  #       requires:
  #         - llama-bot-api-lint
  #         - llama-bot-api-test
  # llama-bot-client:
  #   jobs:
  #     - llama-bot-api-lint
  #     - llama-bot-api-test
  #     - llama-bot-api-build
  #     - llama-bot-api-publish:
  #       - requires:
  #         - llama-bot-api-test
  #         - llama-bot-api-build
