version: 2.1

orbs:
  heroku-orb: circleci/heroku@1.2.6 # Invoke the Heroku orb

executors:
  llama-bot-docker-executor:
    docker:
      - image: cimg/node:14.17.6
    working_directory: ~/llama-bot-discord/llama-bot
      
jobs:
  llama-bot-install:
    executor: llama-bot-docker-executor
    steps:
      - checkout:
          path: ~/llama-bot-discord
      # Try to restore dependencies from cache
      - restore_cache:
          keys:
            - llama-bot-nodemodules-v1-{{ checksum "package-lock.json" }}
            - llama-bot-nodemodules-v1-
      - run:
          name: Install dependencies
          command: npm install
      # Update dependencies cache
      - save_cache:
          key: llama-bot-nodemodules-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      # Save current workflow installed state in cache
      # .Environment.CIRCLE_SHA1 makes it unique for each build
      - save_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./
  llama-bot-lint:
    executor: llama-bot-docker-executor
    steps:
      - restore_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: npm run lint
  llama-bot-test:
    executor: llama-bot-docker-executor
    working_directory: llama-bot
    steps:
      - restore_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build
          command: npm build
  llama-bot-build-publish:
    executor: llama-bot-docker-executor
    working_directory: llama-bot
    environment:
      HEROKU_APP_NAME: "llama-bot"
    steps:
      - restore_cache:
          key: llama-bot-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            git push heroku sequential-branch-filter:master
            heroku run rake db:migrate
            sleep 5 # sleep for 5 seconds to wait for dynos
            heroku restart

workflows:
  version: 2
  llama-bot:
    jobs:
      - llama-bot-install
      - llama-bot-lint:
          requires:
            - llama-bot-install
      - llama-bot-test:
          requires:
            - llama-bot-install
      # - llama-bot-build-publish:
      #   - requires:
      #     - llama-bot-lint
      #     - llama-bot-test
  # llama-bot-api:
  #   jobs:
  #     - llama-bot-api-lint
  #     - llama-bot-api-test
  #     - llama-bot-api-build
  #     - llama-bot-api-publish:
  #       - requires:
  #         - llama-bot-api-test
  #         - llama-bot-api-build
  # llama-bot-client:
  #   jobs:
  #     - llama-bot-api-lint
  #     - llama-bot-api-test
  #     - llama-bot-api-build
  #     - llama-bot-api-publish:
  #       - requires:
  #         - llama-bot-api-test
  #         - llama-bot-api-build
