version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:14.17.6
      
jobs:
  llama-bot-build:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm install
          npm build

workflows:
  my-custom-workflow:
    jobs:
      - llama-bot-build